### ISSUE TITLE
Play peta a missions amb tutorial

### ISSUE THREAD

**Issue by xrubio** [xrubio/simulplay#117]
El backtrace és:

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe25db700 (LWP 3969)]
0x0000000000890379 in GameLevel::getAttributesValues (this=0x1f1d930, k="TECHNOLOGY", i=1) at /home/xrubio/workspace/evPlanet/evolvingPlanet/Classes/GameLevel.cpp:173
173         return attributesValues[k][i];
(gdb) bt
#0  0x0000000000890379 in GameLevel::getAttributesValues (this=0x1f1d930, k="TECHNOLOGY", i=1) at /home/xrubio/workspace/evPlanet/evolvingPlanet/Classes/GameLevel.cpp:173
#1  0x000000000088c7d4 in Reproduce::execute (this=0x2170d80, typeAgent=0, agent=0x1e8f880) at /home/xrubio/workspace/evPlanet/evolvingPlanet/Classes/Reproduce.cpp:39
#2  0x00000000008923dc in GameLevel::act (this=0x1f1d930) at /home/xrubio/workspace/evPlanet/evolvingPlanet/Classes/GameLevel.cpp:714
#3  0x0000000000891252 in GameLevel::playLevel (this=0x1f1d930) at /home/xrubio/workspace/evPlanet/evolvingPlanet/Classes/GameLevel.cpp:518
#4  0x00000000008b61ff in UIGameplayMap::playLevel (this=0x14449c0) at /home/xrubio/workspace/evPlanet/evolvingPlanet/Classes/UIGameplayMap.cpp:1343
#5  0x00000000008b60d2 in UIGameplayMap::createLevel (arg=0x14449c0) at /home/xrubio/workspace/evPlanet/evolvingPlanet/Classes/UIGameplayMap.cpp:1317
#6  0x00007ffff68d6182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#7  0x00007ffff592b47d in clone () from /lib/x86_64-linux-gnu/libc.so.6

**Comment by xrubio** [comment]
És l'accés a atributs no definits, segueix a #119
